"""mctrader-data CLI — backfill orchestration (one-shot, MCT-15 first commit)."""

from __future__ import annotations

import contextlib
import json
import logging
import os
import signal
import socket
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

import click

from mctrader_market.types import Symbol, Timeframe

from mctrader_data.path import derive_partition_path, resolve_data_root
from mctrader_data.policy import PartialFailurePolicy

logger = logging.getLogger("mctrader-data.cli")

# ---------------------------------------------------------------------------
# SIGTERM / SIGINT graceful shutdown (MCT-176 D14 / ADR-030 §D4)
# ---------------------------------------------------------------------------

_SHUTDOWN_REQUESTED = False


def _sigterm_handler(signum: int, frame: object) -> None:
    global _SHUTDOWN_REQUESTED
    _SHUTDOWN_REQUESTED = True
    logger.info("[cli] SIGTERM received — graceful shutdown initiated")


def _register_signal_handlers() -> None:
    """Register SIGTERM + SIGINT → _SHUTDOWN_REQUESTED flag.

    Called at entrypoints for non-asyncio commands (collect daemon).
    env override > YAML default > built-in priority chain applies to
    all config values read after this call.
    """
    signal.signal(signal.SIGTERM, _sigterm_handler)
    signal.signal(signal.SIGINT, _sigterm_handler)


# ---------------------------------------------------------------------------
# YAML config loader (MCT-177 CO-1 — option A)
# ---------------------------------------------------------------------------


def _load_yaml_config() -> dict[str, Any]:
    """Load optional YAML default config layer.

    Reads from ``MCTRADER_CONFIG_PATH`` env (default ``/etc/mctrader/config.yaml``).
    Returns empty dict if the file is absent or unreadable — silent degraded mode.

    Priority chain: env override > YAML default > built-in.
    """
    yaml_path = os.environ.get("MCTRADER_CONFIG_PATH", "/etc/mctrader/config.yaml")
    try:
        path = Path(yaml_path)
        if not path.exists():
            return {}
        import yaml  # optional dep — pyyaml

        return yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except Exception:  # noqa: BLE001
        logger.debug("[cli] YAML config load failed — using built-in defaults only")
        return {}


def _parse_iso_utc(value: str) -> datetime:
    if value.endswith("Z"):
        value = value[:-1] + "+00:00"
    dt = datetime.fromisoformat(value)
    if dt.tzinfo is None:
        raise click.BadParameter(f"naive datetime not allowed: {value!r}")
    if dt.utcoffset() != timedelta(0):
        raise click.BadParameter(f"non-UTC offset not allowed: {value!r}")
    return dt.replace(tzinfo=timezone.utc)


def _last_closed_boundary(now_utc: datetime, timeframe: Timeframe) -> datetime:
    """Return the most recent closed-bar boundary for the timeframe.

    1h: floor to UTC hour. 1d: KST midnight (UTC offset +9).
    """
    if timeframe is Timeframe.D1:
        kst = timezone(timedelta(hours=9))
        kst_now = now_utc.astimezone(kst)
        midnight_kst = kst_now.replace(hour=0, minute=0, second=0, microsecond=0)
        return midnight_kst.astimezone(timezone.utc)
    delta = timeframe.delta
    seconds = int(delta.total_seconds())
    epoch = int(now_utc.timestamp())
    floor_epoch = epoch - (epoch % seconds)
    return datetime.fromtimestamp(floor_epoch, tz=timezone.utc)


def _resolve_node_id(explicit: str | None) -> str:
    """Priority: --node-id CLI > MCTRADER_NODE_ID env var > socket.gethostname(). MCT-129."""
    return explicit or os.environ.get("MCTRADER_NODE_ID") or socket.gethostname()


@click.group()
def main() -> None:
    """mctrader-data CLI."""


@main.command()
@click.option("--exchange", required=True, help='e.g. "bithumb"')
@click.option("--symbol", required=True, help='canonical "{quote}-{base}" e.g. "KRW-BTC"')
@click.option("--tf", "timeframe", required=True, type=click.Choice([t.value for t in Timeframe]))
@click.option("--days", type=int, default=None, help="N days back from --end (mutually exclusive with --start)")
@click.option("--start", "start_iso", type=str, default=None, help="ISO 8601 UTC inclusive")
@click.option("--end", "end_iso", type=str, default=None, help="ISO 8601 UTC exclusive (default = last closed bar)")
@click.option(
    "--policy",
    type=click.Choice([p.value for p in PartialFailurePolicy]),
    default=PartialFailurePolicy.HALT.value,
)
@click.option("--dry-run", is_flag=True, help="Print plan without fetching")
@click.option("--root", type=click.Path(path_type=Path), default=None)
@click.option("--snapshot-id", default=None, help="snapshot_id override (default = autogenerated)")
@click.option(
    "--allow-post-cutoff",
    is_flag=True,
    default=False,
    help=(
        "ADR-026 §D6 escape hatch — allow candle backfill into post-cutoff window "
        "(transaction-derived domain). Default = reject. Operator must explicitly opt-in."
    ),
)
def backfill(
    exchange: str,
    symbol: str,
    timeframe: str,
    days: int | None,
    start_iso: str | None,
    end_iso: str | None,
    policy: str,
    dry_run: bool,
    root: Path | None,
    snapshot_id: str | None,
    allow_post_cutoff: bool,
) -> None:
    """Backfill OHLCV candles for ``[start, end)`` half-open interval.

    ADR-026 §D6 cutoff guard: cutoff timestamp 이후 구간의 candle write 는 default 거부.
    cutoff 이후는 transaction WAL → Compactor → Parquet (Aggregation Core Lib) 가 SSOT.
    operator escape hatch = ``--allow-post-cutoff`` (DR / debug 한정).
    """
    if days is not None and start_iso is not None:
        raise click.UsageError("--days and --start are mutually exclusive")

    sym = Symbol.from_string(symbol)
    tf = Timeframe(timeframe)

    end_utc = _parse_iso_utc(end_iso) if end_iso else _last_closed_boundary(datetime.now(timezone.utc), tf)
    if days is not None:
        if days <= 0:
            raise click.BadParameter("--days must be positive")
        start_utc = end_utc - timedelta(days=days)
    elif start_iso is not None:
        start_utc = _parse_iso_utc(start_iso)
    else:
        raise click.UsageError("must specify either --days or --start")

    if start_utc >= end_utc:
        raise click.BadParameter("start must be < end")

    # ADR-026 §D6 cutoff guard — legacy candle Parquet write 중단 (cutoff 이후).
    # `end_utc > CUTOFF_TIMESTAMP` 이면 candle backfill 이 transaction-derived 영역 침투.
    # default reject — operator 가 `--allow-post-cutoff` 명시 시에만 허용.
    from mctrader_data.cutoff import CUTOFF_TIMESTAMP, is_post_cutoff

    if is_post_cutoff(end_utc) and not allow_post_cutoff:
        raise click.ClickException(
            f"[ADR-026:cutoff] candle backfill rejected: end_utc={end_utc.isoformat()} "
            f">= cutoff={CUTOFF_TIMESTAMP.isoformat()}. "
            f"Post-cutoff candle write disabled — transaction WAL → Compactor → Parquet "
            f"(Aggregation Core Lib) is the SSOT. Use --allow-post-cutoff to override (DR only)."
        )

    root_resolved = resolve_data_root(root_override=root)
    partition_preview = derive_partition_path(
        root=root_resolved,
        exchange=exchange,
        symbol=sym,
        timeframe=tf,
        ts_utc=start_utc,
    )

    plan = {
        "exchange": exchange,
        "symbol": str(sym),
        "timeframe": tf.value,
        "start": start_utc.isoformat().replace("+00:00", "Z"),
        "end": end_utc.isoformat().replace("+00:00", "Z"),
        "policy": policy,
        "root": str(root_resolved),
        "snapshot_id": snapshot_id or "<auto>",
        "first_partition": str(partition_preview),
    }

    if dry_run:
        click.echo("[dry-run] Plan:")
        for key, value in plan.items():
            click.echo(f"  {key}: {value}")
        click.echo("[dry-run] No fetch performed.")
        return

    # MCT-12 retroactive sealing — wire CandleProvider → write_candles + lineage
    # (was previously stub printing "First-commit storage scaffold only").
    import hashlib
    from datetime import datetime as _dt
    from datetime import timezone as _tz

    from mctrader_data.adapters import get_candle_provider

    from mctrader_data.lineage import write_lineage
    from mctrader_data.storage import write_candles

    from mctrader_data.policy import (
        DUPLICATE_SAME_HASH,
        PartialFailurePolicy as _PFP,  # noqa: N814
        PolicyDecision,
        QuarantineReason,
        candle_hash,
        check_duplicate,
        check_gap,
        check_schema,
        check_value_range,
        resolve_decision,
    )

    _policy = _PFP(policy)

    # Policy check #6 — API error retry+halt
    _API_MAX_RETRIES = 3  # noqa: N806
    candles = None
    last_exc: Exception | None = None
    click.echo(f"[backfill] fetching from {exchange} public REST...")
    provider = get_candle_provider(exchange)
    for _attempt in range(1, _API_MAX_RETRIES + 1):
        try:
            candles = provider.get_candles(symbol=sym, timeframe=tf, start=start_utc, end=end_utc)  # type: ignore[union-attr]
            last_exc = None
            break
        except Exception as exc:
            last_exc = exc
            click.echo(
                f"[backfill] API error (attempt {_attempt}/{_API_MAX_RETRIES}): {exc}",
                err=True,
            )
    if last_exc is not None:
        raise click.ClickException(
            f"API call failed after {_API_MAX_RETRIES} retries: {last_exc}"
        )
    assert candles is not None  # guarded by retry loop above

    if not candles:
        raise click.ClickException(
            f"no candles fetched for [{start_utc.isoformat()}, {end_utc.isoformat()})"
        )

    resolved_snapshot = snapshot_id or hashlib.sha256(
        f"{exchange}|{sym}|{tf.value}|{start_utc.isoformat()}|{end_utc.isoformat()}".encode()
    ).hexdigest()[:16]

    # Per-candle policy enforcement before writing.
    # Tracks: last written ts (for gap check), per-ts hash (for dup check).
    _prev_ts = None
    _seen_hashes: dict = {}  # ts_utc → hash of the first written candle at that ts
    _good: list = []        # candles that pass all checks → bulk write at end
    _quarantine: list = []  # candles routed to quarantine
    _skip_count = 0

    for _candle in candles:
        # Policy check #5 — schema mismatch halt
        _schema_reason = check_schema(_candle)
        if _schema_reason is not None:
            _decision = resolve_decision(_schema_reason, _policy)
            if _decision is PolicyDecision.HALT:
                raise click.ClickException(
                    f"[policy:schema_mismatch] HALT at ts={_candle.ts_utc.isoformat()}: "
                    f"required field missing"
                )
            elif _decision is PolicyDecision.QUARANTINE:
                _quarantine.append((_candle, _schema_reason))
                continue
            else:  # SKIP
                click.echo(
                    f"[policy:schema_mismatch] SKIP ts={_candle.ts_utc.isoformat()}", err=True
                )
                _skip_count += 1
                continue

        # Policy check #1 — gap halt
        _gap_reason = check_gap(_prev_ts, _candle.ts_utc, tf)
        if _gap_reason is not None:
            _decision = resolve_decision(_gap_reason, _policy)
            if _decision is PolicyDecision.HALT:
                raise click.ClickException(
                    f"[policy:gap] HALT at ts={_candle.ts_utc.isoformat()}: "
                    f"gap detected (prev={_prev_ts.isoformat() if _prev_ts else None})"
                )
            elif _decision is PolicyDecision.QUARANTINE:
                _quarantine.append((_candle, _gap_reason))
                continue
            else:  # SKIP
                click.echo(
                    f"[policy:gap] SKIP ts={_candle.ts_utc.isoformat()}", err=True
                )
                _skip_count += 1
                continue

        # Policy check #4 — value out-of-range quarantine
        _range_reason = check_value_range(_candle)
        if _range_reason is not None:
            _decision = resolve_decision(_range_reason, _policy)
            if _decision is PolicyDecision.HALT:
                raise click.ClickException(
                    f"[policy:value_range] HALT at ts={_candle.ts_utc.isoformat()}: "
                    f"OHLCV values failed range check"
                )
            elif _decision is PolicyDecision.QUARANTINE:
                _quarantine.append((_candle, _range_reason))
                continue
            else:  # SKIP
                click.echo(
                    f"[policy:value_range] SKIP ts={_candle.ts_utc.isoformat()}", err=True
                )
                _skip_count += 1
                continue

        # Policy checks #2/#3 — duplicate detection (same-hash skip / diff-hash quarantine)
        _incoming_hash = candle_hash(_candle)
        _existing_hash = _seen_hashes.get(_candle.ts_utc)
        _dup_result = check_duplicate(_existing_hash, _incoming_hash)
        if _dup_result == DUPLICATE_SAME_HASH:
            # Same hash → silently skip regardless of policy (idempotent replay)
            click.echo(
                f"[policy:dup_same_hash] SKIP ts={_candle.ts_utc.isoformat()} (hash match)",
                err=True,
            )
            _skip_count += 1
            continue
        elif _dup_result == QuarantineReason.DUPLICATE_DIFFERENT_HASH:
            _decision = resolve_decision(QuarantineReason.DUPLICATE_DIFFERENT_HASH, _policy)
            if _decision is PolicyDecision.HALT:
                raise click.ClickException(
                    f"[policy:dup_diff_hash] HALT at ts={_candle.ts_utc.isoformat()}: "
                    f"hash mismatch for existing record"
                )
            elif _decision is PolicyDecision.QUARANTINE:
                _quarantine.append((_candle, QuarantineReason.DUPLICATE_DIFFERENT_HASH))
                continue
            else:  # SKIP
                click.echo(
                    f"[policy:dup_diff_hash] SKIP ts={_candle.ts_utc.isoformat()}", err=True
                )
                _skip_count += 1
                continue

        # Candle passed all checks — record for normal write
        _seen_hashes[_candle.ts_utc] = _incoming_hash
        _prev_ts = _candle.ts_utc
        _good.append(_candle)

    # Write quarantined candles to quarantine/ sub-directory
    _quarantine_count = len(_quarantine)
    if _quarantine:
        import json as _json

        _quarantine_root = root_resolved / "quarantine"
        _quarantine_root.mkdir(parents=True, exist_ok=True)
        for _q_candle, _q_reason in _quarantine:
            _q_file = (
                _quarantine_root
                / f"{exchange}_{sym}_{tf.value}_{_q_candle.ts_utc.strftime('%Y%m%dT%H%M%SZ')}"
                  f"_{resolved_snapshot}_{_q_reason}.json"
            )
            _q_file.write_text(
                _json.dumps({
                    "reason": str(_q_reason),
                    "snapshot_id": resolved_snapshot,
                    "exchange": exchange,
                    "symbol": str(sym),
                    "timeframe": tf.value,
                    "ts_utc": _q_candle.ts_utc.isoformat(),
                    "open": str(_q_candle.open),
                    "high": str(_q_candle.high),
                    "low": str(_q_candle.low),
                    "close": str(_q_candle.close),
                    "volume": str(_q_candle.volume),
                    "value": str(_q_candle.value) if _q_candle.value is not None else None,
                }, indent=2),
                encoding="utf-8",
            )
        click.echo(
            f"[backfill] quarantined {_quarantine_count} candle(s) → {_quarantine_root}"
        )

    if not _good:
        raise click.ClickException(
            f"all {len(candles)} fetched candles were rejected by policy "
            f"({_quarantine_count} quarantined, {_skip_count} skipped)"
        )

    partition = write_candles(candles=_good, root=root_resolved, snapshot_id=resolved_snapshot)
    parquet_path = partition / f"part-{resolved_snapshot}.parquet"

    request_hash = hashlib.sha256(
        f"{sym}|{tf.value}|{start_utc.isoformat()}|{end_utc.isoformat()}".encode()
    ).hexdigest()
    response_hash = hashlib.sha256(
        "|".join(
            f"{c.ts_utc.isoformat()},{c.open},{c.high},{c.low},{c.close},{c.volume}"
            for c in candles
        ).encode()
    ).hexdigest()

    _endpoint = "https://api.bithumb.com" if exchange == "bithumb" else "https://api.upbit.com"
    _adapter_name = f"mctrader-market-{exchange}"
    _adapter_version = "0.3.0" if exchange == "bithumb" else "0.1.0"
    write_lineage(
        partition_dir=partition,
        snapshot_id=resolved_snapshot,
        exchange=exchange,
        endpoint=_endpoint,
        request_params_hash=request_hash,
        fetched_at_utc=_dt.now(_tz.utc),
        response_hash=response_hash,
        adapter_name=_adapter_name,
        adapter_version=_adapter_version,
    )

    click.echo(f"[backfill] fetched {len(candles)} candles")
    click.echo(
        f"[backfill] policy={policy} written={len(_good)} "
        f"skipped={_skip_count} quarantined={_quarantine_count}"
    )
    click.echo(f"[backfill] window: {start_utc.isoformat()} → {end_utc.isoformat()}")
    click.echo(f"[backfill] partition: {partition}")
    click.echo(f"[backfill] parquet: {parquet_path}")
    click.echo(f"[backfill] snapshot_id: {resolved_snapshot}")
    sys.exit(0)


@main.command()
@click.option(
    "--symbols", default=None,
    help='Explicit symbols comma-separated, e.g. "KRW-BTC,KRW-ETH". Mutex with --top-n.',
)
@click.option(
    "--top-n", type=int, default=None,
    help="Query Bithumb ticker at startup, pick top N by 24h volume. Mutex with --symbols.",
)
@click.option(
    "--include", default="transactions,orderbook,orderbook_snapshot",
    help='Channels comma-separated: "transactions" + "orderbook" + "orderbook_snapshot" (default all three).',
)
@click.option("--exchange", default="bithumb", show_default=True, help="거래소 이름 (bithumb|upbit)")
@click.option(
    "--root", type=click.Path(path_type=Path), default=None,
    help="Storage root. Default: $MCTRADER_DATA_ROOT or ~/.local/share/mctrader/data.",
)
@click.option(
    "--node-id", default=None,
    help="Node identifier for HA active-active (default: socket.gethostname()). "
         "Per MCT-91 — drives node= partition split + heartbeat-{node_id}.json.",
)
@click.option(
    "--heartbeat-interval", default=5.0, type=float,
    help="Heartbeat write interval in seconds (default 5.0).",
)
@click.option(
    "--heartbeat-root", type=click.Path(path_type=Path), default=None,
    help="Heartbeat artifact root (default: same as --root).",
)
@click.option(
    "--health-port", type=int, default=None,
    help="HTTP /health endpoint port (Docker HEALTHCHECK). "
         "Default: $MCTRADER_HEALTH_PORT or 8080. CFP-128 / ADR-033.",
)
@click.option("--log-level", default="INFO", type=click.Choice(["DEBUG", "INFO", "WARNING", "ERROR"]))
def collect(
    symbols: str | None,
    top_n: int | None,
    include: str,
    exchange: str,
    root: Path | None,
    node_id: str | None,
    heartbeat_interval: float,
    heartbeat_root: Path | None,
    health_port: int | None,
    log_level: str,
) -> None:
    """Forward-only WebSocket collector daemon (MCT-58).

    Subscribes to Bithumb public WebSocket for N symbols and writes Parquet
    append-only partitions under ``<root>/market/{ticks,orderbook}/...``.

    Designed for 24/7 systemd operation. SIGTERM = graceful drain + close.
    """
    # MCT-177 CO-2: register SIGTERM/SIGINT → _SHUTDOWN_REQUESTED flag for
    # non-asyncio chunk boundary polling. The asyncio _amain installs its own
    # loop.add_signal_handler(); this call ensures the flag is set regardless
    # of which signal path fires first.
    _register_signal_handlers()

    import asyncio
    import logging

    from mctrader_data.collector import (
        CollectorDaemon,
        MultiSymbolCollector,
        fetch_top_n_krw_symbols,
    )

    logging.basicConfig(
        level=getattr(logging, log_level),
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )
    log = logging.getLogger("mctrader-data.collect")

    if symbols and top_n:
        raise click.UsageError("--symbols and --top-n are mutually exclusive")
    if not symbols and not top_n:
        raise click.UsageError("either --symbols or --top-n must be provided")

    chans = {c.strip() for c in include.split(",") if c.strip()}
    invalid = chans - {"transactions", "orderbook", "orderbook_snapshot"}
    if invalid:
        raise click.BadParameter(f"unknown channel(s): {invalid}")
    include_tx = "transactions" in chans
    include_ob = "orderbook" in chans
    include_ob_snapshot = "orderbook_snapshot" in chans

    root_resolved = resolve_data_root(root_override=root)
    log.info("storage root: %s", root_resolved)

    # MCT-91 — HA active-active resolution (MCT-129: env var priority)
    resolved_node_id = _resolve_node_id(node_id)
    resolved_heartbeat_root = heartbeat_root if heartbeat_root is not None else root_resolved
    log.info(
        "HA: node_id=%s heartbeat_root=%s heartbeat_interval=%.1fs",
        resolved_node_id, resolved_heartbeat_root, heartbeat_interval,
    )

    async def _amain() -> None:
        import asyncio as _asyncio
        import signal as _signal
        from datetime import datetime, timezone

        from mctrader_data.heartbeat import HeartbeatWriter
        from mctrader_data.manifest import CollectorManifest, derive_collector_run_id

        _loop = _asyncio.get_running_loop()
        _current_task = _asyncio.current_task()
        _loop.add_signal_handler(
            _signal.SIGTERM,
            lambda: _current_task.cancel() if _current_task else None,
        )

        if symbols:
            sym_list = [Symbol.from_string(s.strip()) for s in symbols.split(",") if s.strip()]
            selection_method = "explicit"
        else:
            assert top_n is not None  # guarded above by mutex check
            log.info("querying Bithumb ticker for top %d KRW pairs by 24h volume...", top_n)
            sym_list = await fetch_top_n_krw_symbols(n=top_n)
            log.info("selected: %s", [str(s) for s in sym_list])
            selection_method = "top_n_volume"

        started_at = datetime.now(timezone.utc)
        # MCT-91 — HA collector_run_id = {node_id}-{UTC_compact_ts} (legacy hash if node_id=None)
        run_id = derive_collector_run_id(
            started_at_utc=started_at,
            exchange=exchange,
            selected_symbols=[str(s) for s in sym_list],
            node_id=resolved_node_id,
        )
        channels: list[str] = []
        if include_tx:
            channels.append("transaction")
        if include_ob:
            channels.append("orderbookdepth")
        if include_ob_snapshot:
            channels.append("orderbooksnapshot")
        manifest = CollectorManifest(
            collector_run_id=run_id,
            started_at_utc=started_at,
            exchange=exchange,
            selected_symbols=tuple(str(s) for s in sym_list),
            channels=tuple(channels),
            selection_method=selection_method,  # type: ignore[arg-type]
            top_n=top_n,
            node_id=resolved_node_id,
        )

        # MCT-91 — heartbeat writer (HA active-active)
        heartbeat = HeartbeatWriter(
            root=resolved_heartbeat_root,
            node_id=resolved_node_id,
            interval_seconds=heartbeat_interval,
        )

        from mctrader_data.coverage_stats import CoverageStatsWriter
        coverage_writer = CoverageStatsWriter(
            root=root_resolved,
            node_id=resolved_node_id,
            collector_run_id=run_id,
        )
        log.info(
            "[collector] coverage-stats writer initialized: %s",
            root_resolved / "market" / "manifest" / "coverage-stats.json",
        )

        # CFP-128 / ADR-033 Pilot — HealthServer for Docker HEALTHCHECK
        from mctrader_data.health_server import HealthServer
        health = HealthServer(heartbeat_writer=heartbeat, port=health_port)
        log.info("health server bound port=%d", health.port)

        daemons = [
            CollectorDaemon(
                root=root_resolved, exchange=exchange, symbol=sym,
                include_transactions=include_tx, include_orderbook=include_ob,
                include_orderbook_snapshot=include_ob_snapshot,
                snapshot_id=run_id,
                node_id=resolved_node_id, collector_run_id=run_id,
                heartbeat_writer=heartbeat,
                coverage_stats_writer=coverage_writer,
            )
            for sym in sym_list
        ]
        collector = MultiSymbolCollector(
            daemons, manifest=manifest, manifest_root=root_resolved,
            heartbeat_writer=heartbeat,
            health_server=health,
            coverage_stats_writer=coverage_writer,
        )

        # MCT-179 D17 — startup InvariantHarness 8종 scan hook (AC-4)
        # ambiguity invariant (D10) container restart race 방지:
        #   - NAS 없으면 (NAS_MINIO_ENDPOINT 미설정) scan skip (graceful)
        #   - ambiguity fail 시 log.warning (raise 금지 — false positive 방지 per plan §2.1)
        _nas_endpoint = os.environ.get("NAS_MINIO_ENDPOINT")
        if _nas_endpoint:
            try:
                from mctrader_data.nas_storage.nas_uploader import NASUploader as _NASUploader
                from mctrader_data.nas_migration.invariant_harness import (  # noqa: N814
                    InvariantHarness as _InvariantHarness,
                )

                _wal_root = root_resolved / "wal"
                _startup_nas = _NASUploader(
                    endpoint=_nas_endpoint,
                    access_key=os.environ.get("NAS_MINIO_ACCESS_KEY", ""),
                    secret_key=os.environ.get("NAS_MINIO_SECRET_KEY", ""),
                    bucket=os.environ.get("NAS_MINIO_BUCKET", "mctrader-market"),
                    retry_queue=None,  # type: ignore[arg-type]
                )
                _startup_harness = _InvariantHarness(
                    nas_uploader=_startup_nas,
                    local_root=_wal_root,
                )
                # scan: WAL root 하위 partition 디렉터리를 discovery 해 per-partition verify
                # 비어있으면 (wal_root 없거나 partition 0) 스캔 없이 정상 진행
                _scan_partitions: list = []
                if _wal_root.exists():
                    # 2-level depth: wal/{schema_version=*}/{tier=*}/{exchange=*}/{symbol=*}/...
                    # 최하위 parquet dir 탐색 대신 top-level partition (date dir) 기준
                    for _part_dir in sorted(_wal_root.rglob("*.parquet")):
                        _pdir = _part_dir.parent
                        if _pdir not in _scan_partitions:
                            _scan_partitions.append(_pdir)
                if _scan_partitions:
                    _scan_fail_count = 0
                    for _part in _scan_partitions[:20]:  # 최대 20 partition 스캔 (startup latency 제한)
                        try:
                            _nas_prefix = str(_part.relative_to(_wal_root)).replace("\\", "/")
                            _inv_result = _startup_harness.verify(
                                local_partition=_part,
                                nas_partition=_nas_prefix,
                            )
                            if _inv_result.status == "ambiguity_fail":
                                # ambiguity = D10 container restart race 가능성 — log.warning 만 (raise 금지)
                                log.warning(
                                    "[startup-scan] D10 ambiguity invariant WARN "
                                    "(partition=%r) — container restart race 가능성. "
                                    "Manual escalation 권고 (ADR-029 §D10).",
                                    _nas_prefix,
                                )
                                _scan_fail_count += 1
                            elif _inv_result.status != "all_pass":
                                log.info(
                                    "[startup-scan] invariant %s (partition=%r)",
                                    _inv_result.status, _nas_prefix,
                                )
                        except Exception:
                            log.debug("[startup-scan] partition scan error (skipped)", exc_info=True)
                    log.info(
                        "[startup-scan] InvariantHarness 8종 scan 완료: "
                        "scanned=%d ambiguity_warn=%d",
                        min(len(_scan_partitions), 20), _scan_fail_count,
                    )
                else:
                    log.info("[startup-scan] WAL partitions 없음 — startup scan skip")
            except Exception:
                log.warning("[startup-scan] InvariantHarness import/scan 실패 — skip (graceful)", exc_info=True)
        else:
            log.info("[startup-scan] NAS_MINIO_ENDPOINT 미설정 — startup InvariantHarness scan skip")

        # MCT-104 — MetadataRefreshScheduler (daily §D13 refresh, separate task)
        # Only bithumb supports MetadataRefreshScheduler (Upbit has no equivalent endpoint)
        import contextlib as _ctx
        if include_ob_snapshot and exchange == "bithumb":
            from mctrader_data.collector import MetadataRefreshScheduler
            metadata_scheduler = MetadataRefreshScheduler(
                root=root_resolved,
                exchange=exchange,
                node_id=resolved_node_id,
                collector_run_id=run_id,
            )
            metadata_task = _asyncio.create_task(metadata_scheduler.run())
            log.info("[metadata] refresh scheduler started")
        else:
            metadata_task = None

        try:
            await collector.run()
        finally:
            if metadata_task is not None:
                metadata_task.cancel()
                with _ctx.suppress(_asyncio.CancelledError, Exception):
                    await metadata_task
                log.info("[metadata] refresh scheduler shutdown")

    try:
        asyncio.run(_amain())
    except KeyboardInterrupt:
        log.info("KeyboardInterrupt — shutting down")

    # MCT-177 CO-2: loop termination — flush pending WAL writes + clean exit.
    # _SHUTDOWN_REQUESTED flag is set by _sigterm_handler; asyncio path
    # cancels via loop.add_signal_handler() above.  Both paths converge here.
    if _SHUTDOWN_REQUESTED:
        log.info("[collect] SIGTERM shutdown — pending WAL flush complete")
    sys.exit(0)


@main.command("compact")
@click.option("--root", envvar="MCTRADER_DATA_ROOT", required=True, type=click.Path())
@click.option("--once", is_flag=True, default=False, help="Run one scan cycle then exit.")
@click.option("--log-level", default="INFO")
@click.option(
    "--backfill",
    is_flag=True,
    default=False,
    help="MCT-173 D1=B: One-shot backfill mode — process frozen WAL sealed segments into L1 parquets.",
)
@click.option(
    "--exchange",
    default="upbit",
    help="Exchange to backfill (default: upbit, backfill mode only).",
)
@click.option(
    "--tier",
    default="L1",
    help="Tier to produce in backfill mode (default: L1).",
)
@click.option(
    "--channel",
    default="orderbooksnapshot",
    help="WAL channel to backfill (default: orderbooksnapshot).",
)
def compact_cmd(
    root: str,
    once: bool,
    log_level: str,
    backfill: bool,
    exchange: str,
    tier: str,
    channel: str,
) -> None:
    """Run the WAL compactor (L1/L2/L3 tiered compaction).</p>

    Use --backfill to run a one-shot historical materialization pass:
    processes all frozen (sealed, not yet compacted) WAL segments into
    L1 parquets. Idempotent: re-running skips already-compacted segments.
    """
    import asyncio
    import logging
    from pathlib import Path
    from mctrader_data.compactor.metrics_server import start_metrics_server
    from mctrader_data.compactor.runner import CompactorRunner

    logging.basicConfig(
        level=getattr(logging, log_level),
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )

    # MCT-134 — bootstrap /metrics HTTP endpoint (RSS gauge for now; Task 7 will
    # add the remaining 4 metric series). Skip in --once mode (one-shot CLI runs
    # have no scrape window). Port via env: MCTRADER_COMPACTOR_METRICS_PORT.
    log = logging.getLogger("mctrader-data.compact")

    # MCT-173 D1=B: --backfill is a one-shot mode — skip metrics server (no scrape window)
    if not once and not backfill:
        metrics_port = int(os.environ.get("MCTRADER_COMPACTOR_METRICS_PORT", "8080"))
        start_metrics_server(port=metrics_port)

    # MCT-156: NASUploader + DualWriter lazy build (ADR-027 D4/D5 amendment 박제 정합)
    # NAS_MINIO_ENDPOINT 부재 시 = test/local dev mode → dual_writer=None,
    # CompactorRunner 는 L2/L3 NAS upload 0 (degraded mode).
    dual_writer = None
    if os.environ.get("NAS_MINIO_ENDPOINT"):
        from mctrader_data.nas_storage.nas_uploader import NASUploader
        from mctrader_data.nas_storage.dual_writer import DualWriter
        from mctrader_data.nas_storage.retry_queue import RetryQueue

        retry_queue_path = Path(root) / "nas_retry_queue.sqlite"
        retry_queue = RetryQueue(path=retry_queue_path)
        nas_uploader = NASUploader(
            endpoint=os.environ["NAS_MINIO_ENDPOINT"],
            access_key=os.environ["NAS_MINIO_ACCESS_KEY"],
            secret_key=os.environ["NAS_MINIO_SECRET_KEY"],
            bucket=os.environ.get("NAS_MINIO_BUCKET", "mctrader-market"),
            retry_queue=retry_queue,
        )
        dual_writer = DualWriter(nas_uploader=nas_uploader, local_root=Path(root))
        log.info(
            "[compactor] NAS dual-write enabled: endpoint=%s bucket=%s",
            os.environ["NAS_MINIO_ENDPOINT"],
            os.environ.get("NAS_MINIO_BUCKET", "mctrader-market"),
        )
    else:
        log.warning(
            "[compactor] NAS_MINIO_ENDPOINT not set — L2/L3 NAS upload disabled (degraded mode)"
        )

    # MCT-173 D1=B: --backfill mode — one-shot historical materialization
    if backfill:
        from mctrader_data.compactor.runner import run_backfill
        log.info(
            "[backfill] mode activated exchange=%s tier=%s channel=%s root=%s",
            exchange, tier, channel, root,
        )
        result = run_backfill(
            root=Path(root),
            exchange=exchange,
            tier=tier,
            channel=channel,
        )
        log.info(
            "[backfill] DONE processed=%d skipped=%d l1_parquets=%d date=%s~%s",
            result.segments_processed,
            result.segments_skipped,
            result.l1_parquets_created,
            result.date_range_start,
            result.date_range_end,
        )
        click.echo(
            f"[backfill] complete: {result.segments_processed} segments processed, "
            f"{result.l1_parquets_created} L1 parquets created, "
            f"date_range={result.date_range_start}~{result.date_range_end}"
        )
        return

    async def _run() -> None:
        runner = CompactorRunner(Path(root), dual_writer=dual_writer)
        if once:
            await runner._tick()
            return
        try:
            import signal as _signal
            loop = asyncio.get_running_loop()
            task = asyncio.current_task()
            loop.add_signal_handler(_signal.SIGTERM, lambda: task.cancel() if task else None)
        except NotImplementedError:
            pass  # Windows: signal handlers not supported in asyncio
        await runner.run()

    with contextlib.suppress(KeyboardInterrupt):
        asyncio.run(_run())


# ---------------------------------------------------------------------------
# WS-A: promote-historical — date-bounded L1→L2→NAS+L3→NAS one-shot promotion
# ---------------------------------------------------------------------------


@main.command("promote-historical")
@click.option(
    "--root",
    required=True,
    type=click.Path(exists=True, file_okay=False, dir_okay=True),
    help="data root (ex: /var/lib/mctrader/data)",
)
@click.option("--start", "start", required=True, help="start date YYYY-MM-DD (inclusive)")
@click.option("--end", "end", required=True, help="end date YYYY-MM-DD (inclusive)")
@click.option("--exchange", default=None, help="target exchange only (default: auto-discover)")
@click.option(
    "--channel",
    default="orderbooksnapshot",
    show_default=True,
    help="channel to promote (default: orderbooksnapshot, MCT-159 #48 safe)",
)
def promote_historical_cmd(
    root: str,
    start: str,
    end: str,
    exchange: str | None,
    channel: str,
) -> None:
    """WS-A + MCT-204: date-bounded historical L1->L2->NAS+L3->NAS one-shot promotion + L1 reclaim.

    Promotes historical L1 parquets outside the forward window (today/yesterday)
    to L2/L3 tiers, then reclaims L1 local storage per partition.

    MCT-204 Layer 3 guards:
    - INV-B: --end >= today-1 → exit 2 (forward window 진입 차단, breaking change).
    - INV-G: pidfile flock exclusive — concurrent second instance → exit 2.

    exit 1 if counts['errors'] > 0. exit 2 on bad args or concurrency conflict.

    Example::

        python -m mctrader_data.cli promote-historical \\
            --root /var/lib/mctrader/data \\
            --start 2026-05-13 --end 2026-05-15 \\
            --exchange upbit
    """
    import atexit
    import logging
    import signal
    import sys
    from datetime import date as _date, datetime as _datetime, timezone as _timezone, timedelta as _timedelta
    from pathlib import Path

    from mctrader_data.compactor.runner import run_historical_promotion
    from mctrader_data.nas_storage.nas_uploader import NASUploader
    from mctrader_data.nas_storage.dual_writer import DualWriter

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )
    log = logging.getLogger("mctrader-data.promote-historical")

    try:
        start_date = _date.fromisoformat(start)
        end_date = _date.fromisoformat(end)
    except ValueError as exc:
        click.echo(f"[ERROR] invalid date: {exc}", err=True)
        sys.exit(2)

    if start_date > end_date:
        click.echo(
            f"[ERROR] --start {start_date} is after --end {end_date}",
            err=True,
        )
        sys.exit(2)

    # MCT-204 INV-B: forward window guard — abort if end_date >= today-1.
    # Breaking change (MCT-204 §11.5.2 API 분류): operator runbook 인지 의무.
    now_utc = _datetime.now(_timezone.utc).date()
    today_minus_1 = now_utc - _timedelta(days=1)
    if end_date >= today_minus_1:
        click.echo(
            f"[ERROR] --end {end_date} must be < {today_minus_1} (today-1={today_minus_1}). "
            "promote-historical only operates on historical partitions outside the forward window. "
            "(MCT-204 INV-B)",
            err=True,
        )
        sys.exit(2)

    # MCT-204 INV-G: pidfile flock exclusive lock — concurrent instance exit 2.
    # Pattern: MCT-173 BackfillManifest pidfile 동형 (ADR-029 §11.7 정합).
    _audit_dir = Path(root) / "audit"
    _audit_dir.mkdir(parents=True, exist_ok=True)
    _pidfile = _audit_dir / "historical-reclaim.pid"
    _pidfile_fd = None

    def _release_pidfile():
        if _pidfile_fd is not None:
            try:
                import fcntl
                fcntl.flock(_pidfile_fd, fcntl.LOCK_UN)
                os.close(_pidfile_fd)
            except Exception:
                pass
        with contextlib.suppress(Exception):
            _pidfile.unlink(missing_ok=True)

    try:
        import fcntl
        _pidfile_fd = os.open(str(_pidfile), os.O_WRONLY | os.O_CREAT, 0o644)
        try:
            fcntl.flock(_pidfile_fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            click.echo(
                f"[ERROR] Another promote-historical instance is running (pidfile={_pidfile}). "
                "Wait for it to complete or remove the pidfile if it is stale. (MCT-204 INV-G)",
                err=True,
            )
            os.close(_pidfile_fd)
            sys.exit(2)
        # Write PID for visibility
        os.write(_pidfile_fd, str(os.getpid()).encode())
        atexit.register(_release_pidfile)
        # SIGTERM handler: release pidfile before exit
        def _sigterm_handler(signum, frame):  # type: ignore[type-arg]
            _release_pidfile()
            sys.exit(0)
        signal.signal(signal.SIGTERM, _sigterm_handler)
    except ImportError:
        # Windows: fcntl not available — skip pidfile (best-effort on Windows dev)
        log.warning("[promote-historical] fcntl not available — pidfile lock skipped (Windows)")
        _pidfile_fd = None

    # NAS dual-write (same env-var contract as compact_cmd)
    dual_writer = None
    if os.environ.get("NAS_MINIO_ENDPOINT"):
        from mctrader_data.nas_storage.retry_queue import RetryQueue

        retry_queue = RetryQueue(path=Path(root) / "nas_retry_queue.sqlite")
        nas_uploader = NASUploader(
            endpoint=os.environ["NAS_MINIO_ENDPOINT"],
            access_key=os.environ["NAS_MINIO_ACCESS_KEY"],
            secret_key=os.environ["NAS_MINIO_SECRET_KEY"],
            bucket=os.environ.get("NAS_MINIO_BUCKET", "mctrader-market"),
            retry_queue=retry_queue,
        )
        dual_writer = DualWriter(nas_uploader=nas_uploader, local_root=Path(root))
        log.info(
            "[promote-historical] NAS dual-write enabled: endpoint=%s bucket=%s",
            os.environ["NAS_MINIO_ENDPOINT"],
            os.environ.get("NAS_MINIO_BUCKET", "mctrader-market"),
        )

    if dual_writer is None:
        click.echo(
            "[ERROR] NAS_MINIO_ENDPOINT env not set — promote-historical requires DualWriter",
            err=True,
        )
        sys.exit(1)

    log.info(
        "[promote-historical] root=%s start=%s end=%s exchange=%s channel=%s",
        root, start_date, end_date, exchange or "*", channel,
    )

    try:
        counts = run_historical_promotion(
            Path(root),
            start_date=start_date,
            end_date=end_date,
            dual_writer=dual_writer,
            exchange=exchange,
            channel=channel,
        )
    except ValueError as exc:
        # INV-B abort from run_historical_promotion (double guard)
        click.echo(f"[ERROR] {exc}", err=True)
        sys.exit(2)

    click.echo(f"[promote-historical] {counts}")
    log.info(
        "[promote-historical] DONE partitions=%d l2=%d l3=%d skipped=%d errors=%d "
        "l1_reclaim_ok=%d l1_bytes_freed=%d",
        counts["partitions_processed"],
        counts["l2_compacted"],
        counts["l3_compacted"],
        counts["skipped_no_l1"],
        counts["errors"],
        counts.get("l1_reclaim_ok", 0),
        counts.get("l1_bytes_freed", 0),
    )

    sys.exit(0 if counts["errors"] == 0 else 1)


# MCT-93 (X4 of MCT-89) — diagnostic surface


def _level_color(level: int) -> str:
    if level == 0:
        return "\033[32m"  # green
    if level == 1:
        return "\033[33m"  # yellow
    return "\033[31m"  # red


@main.command()
@click.option("--root", type=click.Path(path_type=Path), default=None)
@click.option("--fresh-yellow-seconds", default=10.0, type=float)
@click.option("--fresh-red-seconds", default=30.0, type=float)
@click.option("--lag-yellow-seconds", default=60.0, type=float)
@click.option("--lag-red-seconds", default=300.0, type=float)
@click.option("--format", "fmt", type=click.Choice(["human", "json"]), default="human")
@click.option("--no-color", is_flag=True, help="Disable ANSI color codes (auto-disabled in JSON).")
def status(
    root: Path | None,
    fresh_yellow_seconds: float,
    fresh_red_seconds: float,
    lag_yellow_seconds: float,
    lag_red_seconds: float,
    fmt: str,
    no_color: bool,
) -> None:
    """Show heartbeat freshness / lag / dedup metrics for all nodes.

    Exit code: 0 (all green) / 1 (any yellow) / 2 (any red or no heartbeat).
    """
    import json as _json
    from datetime import datetime as _datetime
    from datetime import timezone as _tz

    root_resolved = resolve_data_root(root_override=root)
    hb_dir = root_resolved / "market" / "manifest"

    files = sorted(hb_dir.glob("heartbeat-*.json"))
    if not files:
        click.echo(f"no heartbeat files in {hb_dir}", err=True)
        sys.exit(2)

    now_wall = _datetime.now(_tz.utc)
    nodes: list[dict] = []
    worst_level = 0

    for f in files:
        node_id = f.stem.removeprefix("heartbeat-")
        try:
            data = _json.loads(f.read_text(encoding="utf-8"))
        except (OSError, _json.JSONDecodeError) as e:
            click.echo(f"failed to read {f}: {e}", err=True)
            worst_level = max(worst_level, 2)
            continue

        try:
            hb_now = _datetime.fromisoformat(data["now"].replace("Z", "+00:00"))
            freshness = (now_wall - hb_now).total_seconds()
        except (KeyError, ValueError):
            freshness = float("inf")

        ws = data.get("ws_state", "unknown")
        node_level = 0
        if ws == "disconnected" or freshness >= fresh_red_seconds:
            node_level = 2
        elif freshness >= fresh_yellow_seconds:
            node_level = 1

        tier_lags: dict[str, float] = {}
        for tier, ts_iso in (data.get("last_event_ts_per_tier") or {}).items():
            try:
                ts = _datetime.fromisoformat(ts_iso.replace("Z", "+00:00"))
                lag = (now_wall - ts).total_seconds()
                tier_lags[tier] = lag
                if lag >= lag_red_seconds:
                    node_level = max(node_level, 2)
                elif lag >= lag_yellow_seconds:
                    node_level = max(node_level, 1)
            except (ValueError, AttributeError):
                continue

        worst_level = max(worst_level, node_level)
        nodes.append({
            "node_id": node_id,
            "freshness_seconds": round(freshness, 1) if freshness != float("inf") else None,
            "ws_state": ws,
            "tier_lags": {k: round(v, 1) for k, v in tier_lags.items()},
            "metrics": data.get("metrics") or {},
            "level": node_level,
        })

    if fmt == "json":
        click.echo(_json.dumps({"nodes": nodes, "worst_level": worst_level}, indent=2))
    else:
        click.echo(f"Heartbeat status (root={root_resolved})")
        click.echo(
            f"{'node_id':<14}{'fresh':<10}{'ws_state':<16}"
            f"{'lag_tick':<12}{'lag_ob':<12}{'dup_skip':<10}{'quarantine':<10}"
        )
        for n in nodes:
            color = "" if no_color else _level_color(n["level"])
            reset = "" if no_color else "\033[0m"
            fresh_str = (
                f"{n['freshness_seconds']:.1f}s" if n["freshness_seconds"] is not None else "—"
            )
            lag_t = n["tier_lags"].get("tick")
            lag_o = n["tier_lags"].get("orderbook")
            click.echo(
                f"{color}{n['node_id']:<14}{fresh_str:<10}{n['ws_state']:<16}"
                f"{(f'{lag_t:.1f}s' if lag_t is not None else '—'):<12}"
                f"{(f'{lag_o:.1f}s' if lag_o is not None else '—'):<12}"
                f"{n['metrics'].get('dup_skip_count', 0):<10}"
                f"{n['metrics'].get('quarantine_count', 0):<10}"
                f"{reset}"
            )

    sys.exit(worst_level)


@main.command("query")
@click.option("--sql", required=True, help="DuckDB SQL to execute against Parquet files")
@click.option(
    "--data-root",
    default=None,
    help="Data root path (default: MCTRADER_DATA_ROOT or /var/lib/mctrader/data)",
)
@click.option("--minio-endpoint", default=None, envvar="MINIO_ENDPOINT", help="MinIO endpoint URL")
@click.option("--minio-access-key", default=None, envvar="MINIO_ACCESS_KEY")
@click.option("--minio-secret-key", default=None, envvar="MINIO_SECRET_KEY")
def query_cmd(
    sql: str,
    data_root: str | None,
    minio_endpoint: str | None,
    minio_access_key: str | None,
    minio_secret_key: str | None,
) -> None:
    """Execute a DuckDB SQL query against local or MinIO Parquet files."""
    import os
    from pathlib import Path
    from mctrader_data.duckdb_reader import DuckDBReader, MinioConfig

    root = Path(data_root or os.environ.get("MCTRADER_DATA_ROOT", "/var/lib/mctrader/data"))
    minio = None
    if minio_endpoint:
        minio = MinioConfig(
            endpoint=minio_endpoint,
            access_key=minio_access_key or "",
            secret_key=minio_secret_key or "",
        )

    reader = DuckDBReader(root=root, minio=minio)
    with reader.open() as conn:
        result = conn.execute(sql)
        columns = [desc[0] for desc in result.description]
        rows = result.fetchall()
        col_widths = [
            max(len(col), max((len(str(row[i])) for row in rows), default=0))
            for i, col in enumerate(columns)
        ]
        header = "  ".join(col.ljust(col_widths[i]) for i, col in enumerate(columns))
        separator = "  ".join("-" * w for w in col_widths)
        print(header)
        print(separator)
        for row in rows:
            print("  ".join(str(row[i]).ljust(col_widths[i]) for i in range(len(columns))))


@main.command("health-check")
@click.option("--target", type=click.Choice(["collector"]), required=True, help="검증 대상")
@click.option("--window", default="5d", show_default=True, help="검증 window (예: 5d, 7d, 30d)")
@click.option("--symbols", multiple=True, help="대상 symbols (omit = bithumb 전체)")
@click.option(
    "--exchanges",
    multiple=True,
    default=["bithumb"],
    show_default=True,
    help="대상 exchanges",
)
@click.option(
    "--tiers",
    multiple=True,
    default=["L1"],
    show_default=True,
    help="대상 tiers (L1/L2/L3)",
)
@click.option(
    "--start-date",
    default="2026-05-09",
    show_default=True,
    help="INV-2 cut-in 기준일 (YYYY-MM-DD)",
)
@click.option(
    "--output",
    type=click.Choice(["json", "csv", "markdown"]),
    default="markdown",
    show_default=True,
)
@click.option(
    "--baseline",
    type=click.Choice(["static", "rolling"]),
    default="static",
    show_default=True,
    help="rolling = NotImplementedError (ADR-028 reserved)",
)
@click.option("--root", type=click.Path(path_type=Path), default=None, help="MCTRADER_DATA_ROOT override")
@click.option("--expected-gib", type=float, default=4.35, show_default=True, help="예상 volume (GiB)")
def health_check(
    target: str,
    window: str,
    symbols: tuple[str, ...],
    exchanges: tuple[str, ...],
    tiers: tuple[str, ...],
    start_date: str,
    output: str,
    baseline: str,
    root: Path | None,
    expected_gib: float,
) -> None:
    """Data accumulation health verification — MCT-165.

    4-layer MVP: volume / gap / file_count / lag.
    INV-1: read-only fs walk (no writes).
    INV-2: start_date = 2026-05-09 cut-in.
    INV-4: exit code 0=ALL PASS, 1=any FAIL, 2=tool error.
    """
    import sys
    from datetime import date as _date, timedelta

    from mctrader_data.health import volume as _vol
    from mctrader_data.health import gap as _gap
    from mctrader_data.health import file_count as _fc
    from mctrader_data.health import lag as _lag
    from mctrader_data.health.report import build_report

    # rolling baseline guard (AC-7 / INV-4 exit code 2)
    if baseline == "rolling":
        try:
            from mctrader_data.health.thresholds import rolling_threshold
            rolling_threshold(0.0)  # always raises
        except NotImplementedError as e:
            click.echo(f"[ERROR] {e}", err=True)
            click.echo(
                "[ERROR] rolling baseline reserved — see docs/adr/ADR-028-rolling-baseline-threshold.md",
                err=True,
            )
            sys.exit(2)

    # parse start_date / window → end_date
    try:
        sd = _date.fromisoformat(start_date)
    except ValueError as e:
        click.echo(f"[ERROR] invalid --start-date: {e}", err=True)
        sys.exit(2)

    try:
        if not window.endswith("d"):
            raise ValueError("window must be in Nd format (e.g., 5d)")
        days = int(window[:-1])
        if days <= 0:
            raise ValueError("window days must be positive")
    except ValueError as e:
        click.echo(f"[ERROR] invalid --window: {e}", err=True)
        sys.exit(2)

    from datetime import date as _date2
    end_date = _date2.today() - timedelta(days=1)  # yesterday (completed day)
    # Clamp: don't go before start_date
    if end_date < sd:
        end_date = sd

    root_resolved = resolve_data_root(root_override=root)
    exchanges_list = list(exchanges)
    tiers_list = list(tiers)

    # Determine symbols: if not specified, discover from L1 bithumb
    if symbols:
        symbols_list = list(symbols)
    else:
        # Auto-discover from L1 bithumb
        symbols_list = []
        l1_base = (
            root_resolved
            / "market"
            / "orderbookdepth"
            / "schema_version=orderbook_depth.v1"
            / "tier=L1"
        )
        for exch in exchanges_list:
            exch_dir = l1_base / f"exchange={exch}"
            if exch_dir.is_dir():
                for sym_dir in sorted(exch_dir.iterdir()):
                    if sym_dir.is_dir() and sym_dir.name.startswith("symbol="):
                        sym_name = sym_dir.name[len("symbol="):]
                        if sym_name not in symbols_list:
                            symbols_list.append(sym_name)

    if not symbols_list:
        click.echo("[WARN] No symbols found — check MCTRADER_DATA_ROOT and --exchanges", err=True)

    try:
        vol_result = _vol.measure_volume(
            root=root_resolved,
            exchanges=exchanges_list,
            symbols=symbols_list,
            tiers=tiers_list,
            start_date=sd,
            end_date=end_date,
        )
        gap_result = _gap.measure_gap(
            root=root_resolved,
            exchanges=exchanges_list,
            symbols=symbols_list,
            tiers=tiers_list,
            start_date=sd,
            end_date=end_date,
        )
        fc_result = _fc.measure_file_count(
            root=root_resolved,
            exchanges=exchanges_list,
            symbols=symbols_list,
            tiers=tiers_list,
            start_date=sd,
            end_date=end_date,
        )
        lag_result = _lag.measure_lag(
            root=root_resolved,
            exchanges=exchanges_list,
        )
    except Exception as e:
        click.echo(f"[ERROR] measurement failed: {e}", err=True)
        sys.exit(2)

    report = build_report(
        volume_result=vol_result,
        gap_result=gap_result,
        file_count_result=fc_result,
        lag_result=lag_result,
        window_start=sd,
        window_end=end_date,
        expected_volume_gib=expected_gib,
        volume_tol=0.20,
        lag_slo_seconds=60.0,
    )

    if output == "json":
        click.echo(report.to_json())
    elif output == "csv":
        click.echo(report.to_csv())
    else:
        click.echo(report.to_markdown())

    # INV-4 exit code
    if report.overall_verdict == "FAIL":
        sys.exit(1)
    sys.exit(0)


@main.command("effective-config")
@click.option(
    "--format",
    "fmt",
    type=click.Choice(["json", "yaml"]),
    default="json",
    show_default=True,
    help="Output format (json or yaml).",
)
def effective_config(fmt: str) -> None:
    """Dump effective configuration (env override > YAML default > built-in).

    MCT-176 D14 — operator verify hook: run inside container to confirm env
    values are applied on top of built-in defaults.

    MCT-177 CO-1: YAML default layer restored. Priority chain:
    ``env override > YAML default > built-in``.
    YAML path: ``MCTRADER_CONFIG_PATH`` env (default ``/etc/mctrader/config.yaml``).
    """
    # Load YAML default layer (empty dict if file absent)
    yaml_cfg = _load_yaml_config()

    def _get(env_key: str, yaml_keys: tuple[str, ...], built_in: Any) -> Any:
        """Resolve a single value: env > yaml > built-in."""
        env_val = os.environ.get(env_key)
        if env_val is not None:
            return env_val
        # Walk yaml_keys as dot-path into yaml_cfg
        node: Any = yaml_cfg
        for k in yaml_keys:
            if not isinstance(node, dict):
                node = None
                break
            node = node.get(k)
        if node is not None:
            return node
        return built_in

    # Resolve ingestion.modes: env CSV string > yaml list/string > built-in CSV
    _ingest_env = os.environ.get("INGEST_MODES")
    _ingest_yaml = (yaml_cfg.get("ingestion") or {}).get("modes")
    if _ingest_env is not None:
        _modes: list[str] = _ingest_env.split(",")
    elif _ingest_yaml is not None:
        _modes = _ingest_yaml if isinstance(_ingest_yaml, list) else str(_ingest_yaml).split(",")
    else:
        _modes = ["transactions", "orderbook"]

    config: dict = {
        "nas_minio": {
            "endpoint": _get("NAS_MINIO_ENDPOINT", ("nas_minio", "endpoint"), "<unset>"),
            "access_key_set": bool(
                os.environ.get("NAS_MINIO_ACCESS_KEY")
                or (yaml_cfg.get("nas_minio") or {}).get("access_key")
            ),
            "secret_key_set": bool(
                os.environ.get("NAS_MINIO_SECRET_KEY")
                or (yaml_cfg.get("nas_minio") or {}).get("secret_key")
            ),
            "bucket": _get("NAS_MINIO_BUCKET", ("nas_minio", "bucket"), "mctrader-market"),
        },
        "wal": {
            "root": _get("MCTRADER_DATA_ROOT", ("wal", "root"), "/var/lib/mctrader/data"),
            "capacity_gb": int(_get("WAL_CAPACITY_GB", ("wal", "capacity_gb"), "30")),
        },
        "ingestion": {
            "top_n": int(_get("UNIVERSE_TOP_N", ("ingestion", "top_n"), "10")),
            "modes": _modes,
        },
        "source_order": ["env", "yaml_default", "built_in"],
    }
    if fmt == "yaml":
        import yaml  # optional dep — pyyaml
        click.echo(yaml.safe_dump(config, sort_keys=False))
    else:
        click.echo(json.dumps(config, indent=2))


if __name__ == "__main__":  # pragma: no cover
    main()
