"""mctrader-data CLI — backfill orchestration (one-shot, MCT-15 first commit)."""

from __future__ import annotations

import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import click

from mctrader_market.types import Symbol, Timeframe

from mctrader_data.path import derive_partition_path, resolve_data_root
from mctrader_data.policy import PartialFailurePolicy
import contextlib


def _parse_iso_utc(value: str) -> datetime:
    if value.endswith("Z"):
        value = value[:-1] + "+00:00"
    dt = datetime.fromisoformat(value)
    if dt.tzinfo is None:
        raise click.BadParameter(f"naive datetime not allowed: {value!r}")
    if dt.utcoffset() != timedelta(0):
        raise click.BadParameter(f"non-UTC offset not allowed: {value!r}")
    return dt.replace(tzinfo=timezone.utc)


def _last_closed_boundary(now_utc: datetime, timeframe: Timeframe) -> datetime:
    """Return the most recent closed-bar boundary for the timeframe.

    1h: floor to UTC hour. 1d: KST midnight (UTC offset +9).
    """
    if timeframe is Timeframe.D1:
        kst = timezone(timedelta(hours=9))
        kst_now = now_utc.astimezone(kst)
        midnight_kst = kst_now.replace(hour=0, minute=0, second=0, microsecond=0)
        return midnight_kst.astimezone(timezone.utc)
    delta = timeframe.delta
    seconds = int(delta.total_seconds())
    epoch = int(now_utc.timestamp())
    floor_epoch = epoch - (epoch % seconds)
    return datetime.fromtimestamp(floor_epoch, tz=timezone.utc)


@click.group()
def main() -> None:
    """mctrader-data CLI."""


@main.command()
@click.option("--exchange", required=True, help='e.g. "bithumb"')
@click.option("--symbol", required=True, help='canonical "{quote}-{base}" e.g. "KRW-BTC"')
@click.option("--tf", "timeframe", required=True, type=click.Choice([t.value for t in Timeframe]))
@click.option("--days", type=int, default=None, help="N days back from --end (mutually exclusive with --start)")
@click.option("--start", "start_iso", type=str, default=None, help="ISO 8601 UTC inclusive")
@click.option("--end", "end_iso", type=str, default=None, help="ISO 8601 UTC exclusive (default = last closed bar)")
@click.option(
    "--policy",
    type=click.Choice([p.value for p in PartialFailurePolicy]),
    default=PartialFailurePolicy.HALT.value,
)
@click.option("--dry-run", is_flag=True, help="Print plan without fetching")
@click.option("--root", type=click.Path(path_type=Path), default=None)
@click.option("--snapshot-id", default=None, help="snapshot_id override (default = autogenerated)")
def backfill(
    exchange: str,
    symbol: str,
    timeframe: str,
    days: int | None,
    start_iso: str | None,
    end_iso: str | None,
    policy: str,
    dry_run: bool,
    root: Path | None,
    snapshot_id: str | None,
) -> None:
    """Backfill OHLCV candles for ``[start, end)`` half-open interval."""
    if days is not None and start_iso is not None:
        raise click.UsageError("--days and --start are mutually exclusive")

    sym = Symbol.from_string(symbol)
    tf = Timeframe(timeframe)

    end_utc = _parse_iso_utc(end_iso) if end_iso else _last_closed_boundary(datetime.now(timezone.utc), tf)
    if days is not None:
        if days <= 0:
            raise click.BadParameter("--days must be positive")
        start_utc = end_utc - timedelta(days=days)
    elif start_iso is not None:
        start_utc = _parse_iso_utc(start_iso)
    else:
        raise click.UsageError("must specify either --days or --start")

    if start_utc >= end_utc:
        raise click.BadParameter("start must be < end")

    root_resolved = resolve_data_root(root_override=root)
    partition_preview = derive_partition_path(
        root=root_resolved,
        exchange=exchange,
        symbol=sym,
        timeframe=tf,
        ts_utc=start_utc,
    )

    plan = {
        "exchange": exchange,
        "symbol": str(sym),
        "timeframe": tf.value,
        "start": start_utc.isoformat().replace("+00:00", "Z"),
        "end": end_utc.isoformat().replace("+00:00", "Z"),
        "policy": policy,
        "root": str(root_resolved),
        "snapshot_id": snapshot_id or "<auto>",
        "first_partition": str(partition_preview),
    }

    if dry_run:
        click.echo("[dry-run] Plan:")
        for key, value in plan.items():
            click.echo(f"  {key}: {value}")
        click.echo("[dry-run] No fetch performed.")
        return

    # MCT-12 retroactive sealing — wire BithumbCandleProvider → write_candles + lineage
    # (was previously stub printing "First-commit storage scaffold only").
    if exchange != "bithumb":
        raise click.UsageError(f"only 'bithumb' exchange is supported in v1, got {exchange!r}")

    import hashlib
    from datetime import datetime as _dt
    from datetime import timezone as _tz

    from mctrader_market_bithumb.adapter import BithumbCandleProvider

    from mctrader_data.lineage import write_lineage
    from mctrader_data.storage import write_candles

    from mctrader_data.policy import (
        DUPLICATE_SAME_HASH,
        PartialFailurePolicy as _PFP,  # noqa: N814
        PolicyDecision,
        QuarantineReason,
        candle_hash,
        check_duplicate,
        check_gap,
        check_schema,
        check_value_range,
        resolve_decision,
    )

    _policy = _PFP(policy)

    # Policy check #6 — API error retry+halt
    _API_MAX_RETRIES = 3  # noqa: N806
    candles = None
    last_exc: Exception | None = None
    click.echo("[backfill] fetching from Bithumb public REST...")
    provider = BithumbCandleProvider()
    for _attempt in range(1, _API_MAX_RETRIES + 1):
        try:
            candles = provider.get_candles(symbol=sym, timeframe=tf, start=start_utc, end=end_utc)
            last_exc = None
            break
        except Exception as exc:
            last_exc = exc
            click.echo(
                f"[backfill] API error (attempt {_attempt}/{_API_MAX_RETRIES}): {exc}",
                err=True,
            )
    if last_exc is not None:
        raise click.ClickException(
            f"API call failed after {_API_MAX_RETRIES} retries: {last_exc}"
        )
    assert candles is not None  # guarded by retry loop above

    if not candles:
        raise click.ClickException(
            f"no candles fetched for [{start_utc.isoformat()}, {end_utc.isoformat()})"
        )

    resolved_snapshot = snapshot_id or hashlib.sha256(
        f"{exchange}|{sym}|{tf.value}|{start_utc.isoformat()}|{end_utc.isoformat()}".encode()
    ).hexdigest()[:16]

    # Per-candle policy enforcement before writing.
    # Tracks: last written ts (for gap check), per-ts hash (for dup check).
    _prev_ts = None
    _seen_hashes: dict = {}  # ts_utc → hash of the first written candle at that ts
    _good: list = []        # candles that pass all checks → bulk write at end
    _quarantine: list = []  # candles routed to quarantine
    _skip_count = 0

    for _candle in candles:
        # Policy check #5 — schema mismatch halt
        _schema_reason = check_schema(_candle)
        if _schema_reason is not None:
            _decision = resolve_decision(_schema_reason, _policy)
            if _decision is PolicyDecision.HALT:
                raise click.ClickException(
                    f"[policy:schema_mismatch] HALT at ts={_candle.ts_utc.isoformat()}: "
                    f"required field missing"
                )
            elif _decision is PolicyDecision.QUARANTINE:
                _quarantine.append((_candle, _schema_reason))
                continue
            else:  # SKIP
                click.echo(
                    f"[policy:schema_mismatch] SKIP ts={_candle.ts_utc.isoformat()}", err=True
                )
                _skip_count += 1
                continue

        # Policy check #1 — gap halt
        _gap_reason = check_gap(_prev_ts, _candle.ts_utc, tf)
        if _gap_reason is not None:
            _decision = resolve_decision(_gap_reason, _policy)
            if _decision is PolicyDecision.HALT:
                raise click.ClickException(
                    f"[policy:gap] HALT at ts={_candle.ts_utc.isoformat()}: "
                    f"gap detected (prev={_prev_ts.isoformat() if _prev_ts else None})"
                )
            elif _decision is PolicyDecision.QUARANTINE:
                _quarantine.append((_candle, _gap_reason))
                continue
            else:  # SKIP
                click.echo(
                    f"[policy:gap] SKIP ts={_candle.ts_utc.isoformat()}", err=True
                )
                _skip_count += 1
                continue

        # Policy check #4 — value out-of-range quarantine
        _range_reason = check_value_range(_candle)
        if _range_reason is not None:
            _decision = resolve_decision(_range_reason, _policy)
            if _decision is PolicyDecision.HALT:
                raise click.ClickException(
                    f"[policy:value_range] HALT at ts={_candle.ts_utc.isoformat()}: "
                    f"OHLCV values failed range check"
                )
            elif _decision is PolicyDecision.QUARANTINE:
                _quarantine.append((_candle, _range_reason))
                continue
            else:  # SKIP
                click.echo(
                    f"[policy:value_range] SKIP ts={_candle.ts_utc.isoformat()}", err=True
                )
                _skip_count += 1
                continue

        # Policy checks #2/#3 — duplicate detection (same-hash skip / diff-hash quarantine)
        _incoming_hash = candle_hash(_candle)
        _existing_hash = _seen_hashes.get(_candle.ts_utc)
        _dup_result = check_duplicate(_existing_hash, _incoming_hash)
        if _dup_result == DUPLICATE_SAME_HASH:
            # Same hash → silently skip regardless of policy (idempotent replay)
            click.echo(
                f"[policy:dup_same_hash] SKIP ts={_candle.ts_utc.isoformat()} (hash match)",
                err=True,
            )
            _skip_count += 1
            continue
        elif _dup_result == QuarantineReason.DUPLICATE_DIFFERENT_HASH:
            _decision = resolve_decision(QuarantineReason.DUPLICATE_DIFFERENT_HASH, _policy)
            if _decision is PolicyDecision.HALT:
                raise click.ClickException(
                    f"[policy:dup_diff_hash] HALT at ts={_candle.ts_utc.isoformat()}: "
                    f"hash mismatch for existing record"
                )
            elif _decision is PolicyDecision.QUARANTINE:
                _quarantine.append((_candle, QuarantineReason.DUPLICATE_DIFFERENT_HASH))
                continue
            else:  # SKIP
                click.echo(
                    f"[policy:dup_diff_hash] SKIP ts={_candle.ts_utc.isoformat()}", err=True
                )
                _skip_count += 1
                continue

        # Candle passed all checks — record for normal write
        _seen_hashes[_candle.ts_utc] = _incoming_hash
        _prev_ts = _candle.ts_utc
        _good.append(_candle)

    # Write quarantined candles to quarantine/ sub-directory
    _quarantine_count = len(_quarantine)
    if _quarantine:
        import json as _json

        _quarantine_root = root_resolved / "quarantine"
        _quarantine_root.mkdir(parents=True, exist_ok=True)
        for _q_candle, _q_reason in _quarantine:
            _q_file = (
                _quarantine_root
                / f"{exchange}_{sym}_{tf.value}_{_q_candle.ts_utc.strftime('%Y%m%dT%H%M%SZ')}"
                  f"_{resolved_snapshot}_{_q_reason}.json"
            )
            _q_file.write_text(
                _json.dumps({
                    "reason": str(_q_reason),
                    "snapshot_id": resolved_snapshot,
                    "exchange": exchange,
                    "symbol": str(sym),
                    "timeframe": tf.value,
                    "ts_utc": _q_candle.ts_utc.isoformat(),
                    "open": str(_q_candle.open),
                    "high": str(_q_candle.high),
                    "low": str(_q_candle.low),
                    "close": str(_q_candle.close),
                    "volume": str(_q_candle.volume),
                    "value": str(_q_candle.value) if _q_candle.value is not None else None,
                }, indent=2),
                encoding="utf-8",
            )
        click.echo(
            f"[backfill] quarantined {_quarantine_count} candle(s) → {_quarantine_root}"
        )

    if not _good:
        raise click.ClickException(
            f"all {len(candles)} fetched candles were rejected by policy "
            f"({_quarantine_count} quarantined, {_skip_count} skipped)"
        )

    partition = write_candles(candles=_good, root=root_resolved, snapshot_id=resolved_snapshot)
    parquet_path = partition / f"part-{resolved_snapshot}.parquet"

    request_hash = hashlib.sha256(
        f"{sym}|{tf.value}|{start_utc.isoformat()}|{end_utc.isoformat()}".encode()
    ).hexdigest()
    response_hash = hashlib.sha256(
        "|".join(
            f"{c.ts_utc.isoformat()},{c.open},{c.high},{c.low},{c.close},{c.volume}"
            for c in candles
        ).encode()
    ).hexdigest()

    write_lineage(
        partition_dir=partition,
        snapshot_id=resolved_snapshot,
        exchange=exchange,
        endpoint="https://api.bithumb.com",
        request_params_hash=request_hash,
        fetched_at_utc=_dt.now(_tz.utc),
        response_hash=response_hash,
        adapter_name="mctrader-market-bithumb",
        adapter_version="0.3.0",
    )

    click.echo(f"[backfill] fetched {len(candles)} candles")
    click.echo(
        f"[backfill] policy={policy} written={len(_good)} "
        f"skipped={_skip_count} quarantined={_quarantine_count}"
    )
    click.echo(f"[backfill] window: {start_utc.isoformat()} → {end_utc.isoformat()}")
    click.echo(f"[backfill] partition: {partition}")
    click.echo(f"[backfill] parquet: {parquet_path}")
    click.echo(f"[backfill] snapshot_id: {resolved_snapshot}")
    sys.exit(0)


@main.command()
@click.option(
    "--symbols", default=None,
    help='Explicit symbols comma-separated, e.g. "KRW-BTC,KRW-ETH". Mutex with --top-n.',
)
@click.option(
    "--top-n", type=int, default=None,
    help="Query Bithumb ticker at startup, pick top N by 24h volume. Mutex with --symbols.",
)
@click.option(
    "--include", default="transactions,orderbook,orderbook_snapshot",
    help='Channels comma-separated: "transactions" + "orderbook" + "orderbook_snapshot" (default all three).',
)
@click.option("--exchange", default="bithumb", help='Only "bithumb" supported in v1.')
@click.option(
    "--root", type=click.Path(path_type=Path), default=None,
    help="Storage root. Default: $MCTRADER_DATA_ROOT or ~/.local/share/mctrader/data.",
)
@click.option(
    "--node-id", default=None,
    help="Node identifier for HA active-active (default: socket.gethostname()). "
         "Per MCT-91 — drives node= partition split + heartbeat-{node_id}.json.",
)
@click.option(
    "--heartbeat-interval", default=5.0, type=float,
    help="Heartbeat write interval in seconds (default 5.0).",
)
@click.option(
    "--heartbeat-root", type=click.Path(path_type=Path), default=None,
    help="Heartbeat artifact root (default: same as --root).",
)
@click.option(
    "--health-port", type=int, default=None,
    help="HTTP /health endpoint port (Docker HEALTHCHECK). "
         "Default: $MCTRADER_HEALTH_PORT or 8080. CFP-128 / ADR-033.",
)
@click.option("--log-level", default="INFO", type=click.Choice(["DEBUG", "INFO", "WARNING", "ERROR"]))
def collect(
    symbols: str | None,
    top_n: int | None,
    include: str,
    exchange: str,
    root: Path | None,
    node_id: str | None,
    heartbeat_interval: float,
    heartbeat_root: Path | None,
    health_port: int | None,
    log_level: str,
) -> None:
    """Forward-only WebSocket collector daemon (MCT-58).

    Subscribes to Bithumb public WebSocket for N symbols and writes Parquet
    append-only partitions under ``<root>/market/{ticks,orderbook}/...``.

    Designed for 24/7 systemd operation. SIGTERM = graceful drain + close.
    """
    import asyncio
    import logging

    from mctrader_data.collector import (
        CollectorDaemon,
        MultiSymbolCollector,
        fetch_top_n_krw_symbols,
    )

    logging.basicConfig(
        level=getattr(logging, log_level),
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )
    log = logging.getLogger("mctrader-data.collect")

    if symbols and top_n:
        raise click.UsageError("--symbols and --top-n are mutually exclusive")
    if not symbols and not top_n:
        raise click.UsageError("either --symbols or --top-n must be provided")

    chans = {c.strip() for c in include.split(",") if c.strip()}
    invalid = chans - {"transactions", "orderbook", "orderbook_snapshot"}
    if invalid:
        raise click.BadParameter(f"unknown channel(s): {invalid}")
    include_tx = "transactions" in chans
    include_ob = "orderbook" in chans
    include_ob_snapshot = "orderbook_snapshot" in chans

    root_resolved = resolve_data_root(root_override=root)
    log.info("storage root: %s", root_resolved)

    # MCT-91 — HA active-active resolution
    import socket as _socket
    resolved_node_id = node_id if node_id is not None else _socket.gethostname()
    resolved_heartbeat_root = heartbeat_root if heartbeat_root is not None else root_resolved
    log.info(
        "HA: node_id=%s heartbeat_root=%s heartbeat_interval=%.1fs",
        resolved_node_id, resolved_heartbeat_root, heartbeat_interval,
    )

    async def _amain() -> None:
        import asyncio as _asyncio
        import signal as _signal
        from datetime import datetime, timezone

        from mctrader_data.heartbeat import HeartbeatWriter
        from mctrader_data.manifest import CollectorManifest, derive_collector_run_id

        _loop = _asyncio.get_running_loop()
        _current_task = _asyncio.current_task()
        _loop.add_signal_handler(
            _signal.SIGTERM,
            lambda: _current_task.cancel() if _current_task else None,
        )

        if symbols:
            sym_list = [Symbol.from_string(s.strip()) for s in symbols.split(",") if s.strip()]
            selection_method = "explicit"
        else:
            assert top_n is not None  # guarded above by mutex check
            log.info("querying Bithumb ticker for top %d KRW pairs by 24h volume...", top_n)
            sym_list = await fetch_top_n_krw_symbols(n=top_n)
            log.info("selected: %s", [str(s) for s in sym_list])
            selection_method = "top_n_volume"

        started_at = datetime.now(timezone.utc)
        # MCT-91 — HA collector_run_id = {node_id}-{UTC_compact_ts} (legacy hash if node_id=None)
        run_id = derive_collector_run_id(
            started_at_utc=started_at,
            exchange=exchange,
            selected_symbols=[str(s) for s in sym_list],
            node_id=resolved_node_id,
        )
        channels: list[str] = []
        if include_tx:
            channels.append("transaction")
        if include_ob:
            channels.append("orderbookdepth")
        if include_ob_snapshot:
            channels.append("orderbooksnapshot")
        manifest = CollectorManifest(
            collector_run_id=run_id,
            started_at_utc=started_at,
            exchange=exchange,
            selected_symbols=[str(s) for s in sym_list],
            channels=channels,
            selection_method=selection_method,  # type: ignore[arg-type]
            top_n=top_n,
            node_id=resolved_node_id,
        )

        # MCT-91 — heartbeat writer (HA active-active)
        heartbeat = HeartbeatWriter(
            root=resolved_heartbeat_root,
            node_id=resolved_node_id,
            interval_seconds=heartbeat_interval,
        )

        from mctrader_data.coverage_stats import CoverageStatsWriter
        coverage_writer = CoverageStatsWriter(
            root=root_resolved,
            node_id=resolved_node_id,
            collector_run_id=run_id,
        )
        log.info(
            "[collector] coverage-stats writer initialized: %s",
            root_resolved / "market" / "manifest" / "coverage-stats.json",
        )

        # CFP-128 / ADR-033 Pilot — HealthServer for Docker HEALTHCHECK
        from mctrader_data.health_server import HealthServer
        health = HealthServer(heartbeat_writer=heartbeat, port=health_port)
        log.info("health server bound port=%d", health.port)

        daemons = [
            CollectorDaemon(
                root=root_resolved, exchange=exchange, symbol=sym,
                include_transactions=include_tx, include_orderbook=include_ob,
                include_orderbook_snapshot=include_ob_snapshot,
                snapshot_id=run_id,
                node_id=resolved_node_id, collector_run_id=run_id,
                heartbeat_writer=heartbeat,
                coverage_stats_writer=coverage_writer,
            )
            for sym in sym_list
        ]
        collector = MultiSymbolCollector(
            daemons, manifest=manifest, manifest_root=root_resolved,
            heartbeat_writer=heartbeat,
            health_server=health,
            coverage_stats_writer=coverage_writer,
        )

        # MCT-104 — MetadataRefreshScheduler (daily §D13 refresh, separate task)
        import contextlib as _ctx
        if include_ob_snapshot:
            from mctrader_data.collector import MetadataRefreshScheduler
            metadata_scheduler = MetadataRefreshScheduler(
                root=root_resolved,
                exchange=exchange,
                node_id=resolved_node_id,
                collector_run_id=run_id,
            )
            metadata_task = _asyncio.create_task(metadata_scheduler.run())
            log.info("[metadata] refresh scheduler started")
        else:
            metadata_task = None

        try:
            await collector.run()
        finally:
            if metadata_task is not None:
                metadata_task.cancel()
                with _ctx.suppress(_asyncio.CancelledError, Exception):
                    await metadata_task
                log.info("[metadata] refresh scheduler shutdown")

    try:
        asyncio.run(_amain())
    except KeyboardInterrupt:
        log.info("KeyboardInterrupt — shutting down")
        sys.exit(0)


@main.command("compact")
@click.option("--root", envvar="MCTRADER_DATA_ROOT", required=True, type=click.Path())
@click.option("--once", is_flag=True, default=False, help="Run one scan cycle then exit.")
@click.option("--log-level", default="INFO")
def compact_cmd(root: str, once: bool, log_level: str) -> None:
    """Run the WAL compactor (L1/L2/L3 tiered compaction)."""
    import asyncio
    import logging
    from pathlib import Path
    from mctrader_data.compactor.runner import CompactorRunner

    logging.basicConfig(
        level=getattr(logging, log_level),
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )

    async def _run() -> None:
        runner = CompactorRunner(Path(root))
        if once:
            await runner._tick()
            return
        try:
            import signal as _signal
            loop = asyncio.get_running_loop()
            task = asyncio.current_task()
            loop.add_signal_handler(_signal.SIGTERM, lambda: task.cancel() if task else None)
        except NotImplementedError:
            pass  # Windows: signal handlers not supported in asyncio
        await runner.run()

    with contextlib.suppress(KeyboardInterrupt):
        asyncio.run(_run())


# MCT-93 (X4 of MCT-89) — diagnostic surface


def _level_color(level: int) -> str:
    if level == 0:
        return "\033[32m"  # green
    if level == 1:
        return "\033[33m"  # yellow
    return "\033[31m"  # red


@main.command()
@click.option("--root", type=click.Path(path_type=Path), default=None)
@click.option("--fresh-yellow-seconds", default=10.0, type=float)
@click.option("--fresh-red-seconds", default=30.0, type=float)
@click.option("--lag-yellow-seconds", default=60.0, type=float)
@click.option("--lag-red-seconds", default=300.0, type=float)
@click.option("--format", "fmt", type=click.Choice(["human", "json"]), default="human")
@click.option("--no-color", is_flag=True, help="Disable ANSI color codes (auto-disabled in JSON).")
def status(
    root: Path | None,
    fresh_yellow_seconds: float,
    fresh_red_seconds: float,
    lag_yellow_seconds: float,
    lag_red_seconds: float,
    fmt: str,
    no_color: bool,
) -> None:
    """Show heartbeat freshness / lag / dedup metrics for all nodes.

    Exit code: 0 (all green) / 1 (any yellow) / 2 (any red or no heartbeat).
    """
    import json as _json
    from datetime import datetime as _datetime
    from datetime import timezone as _tz

    root_resolved = resolve_data_root(root_override=root)
    hb_dir = root_resolved / "market" / "manifest"

    files = sorted(hb_dir.glob("heartbeat-*.json"))
    if not files:
        click.echo(f"no heartbeat files in {hb_dir}", err=True)
        sys.exit(2)

    now_wall = _datetime.now(_tz.utc)
    nodes: list[dict] = []
    worst_level = 0

    for f in files:
        node_id = f.stem.removeprefix("heartbeat-")
        try:
            data = _json.loads(f.read_text(encoding="utf-8"))
        except (OSError, _json.JSONDecodeError) as e:
            click.echo(f"failed to read {f}: {e}", err=True)
            worst_level = max(worst_level, 2)
            continue

        try:
            hb_now = _datetime.fromisoformat(data["now"].replace("Z", "+00:00"))
            freshness = (now_wall - hb_now).total_seconds()
        except (KeyError, ValueError):
            freshness = float("inf")

        ws = data.get("ws_state", "unknown")
        node_level = 0
        if ws == "disconnected" or freshness >= fresh_red_seconds:
            node_level = 2
        elif freshness >= fresh_yellow_seconds:
            node_level = 1

        tier_lags: dict[str, float] = {}
        for tier, ts_iso in (data.get("last_event_ts_per_tier") or {}).items():
            try:
                ts = _datetime.fromisoformat(ts_iso.replace("Z", "+00:00"))
                lag = (now_wall - ts).total_seconds()
                tier_lags[tier] = lag
                if lag >= lag_red_seconds:
                    node_level = max(node_level, 2)
                elif lag >= lag_yellow_seconds:
                    node_level = max(node_level, 1)
            except (ValueError, AttributeError):
                continue

        worst_level = max(worst_level, node_level)
        nodes.append({
            "node_id": node_id,
            "freshness_seconds": round(freshness, 1) if freshness != float("inf") else None,
            "ws_state": ws,
            "tier_lags": {k: round(v, 1) for k, v in tier_lags.items()},
            "metrics": data.get("metrics") or {},
            "level": node_level,
        })

    if fmt == "json":
        click.echo(_json.dumps({"nodes": nodes, "worst_level": worst_level}, indent=2))
    else:
        click.echo(f"Heartbeat status (root={root_resolved})")
        click.echo(
            f"{'node_id':<14}{'fresh':<10}{'ws_state':<16}"
            f"{'lag_tick':<12}{'lag_ob':<12}{'dup_skip':<10}{'quarantine':<10}"
        )
        for n in nodes:
            color = "" if no_color else _level_color(n["level"])
            reset = "" if no_color else "\033[0m"
            fresh_str = (
                f"{n['freshness_seconds']:.1f}s" if n["freshness_seconds"] is not None else "—"
            )
            lag_t = n["tier_lags"].get("tick")
            lag_o = n["tier_lags"].get("orderbook")
            click.echo(
                f"{color}{n['node_id']:<14}{fresh_str:<10}{n['ws_state']:<16}"
                f"{(f'{lag_t:.1f}s' if lag_t is not None else '—'):<12}"
                f"{(f'{lag_o:.1f}s' if lag_o is not None else '—'):<12}"
                f"{n['metrics'].get('dup_skip_count', 0):<10}"
                f"{n['metrics'].get('quarantine_count', 0):<10}"
                f"{reset}"
            )

    sys.exit(worst_level)


@main.command("query")
@click.option("--sql", required=True, help="DuckDB SQL to execute against Parquet files")
@click.option("--data-root", default=None, help="Data root path (default: MCTRADER_DATA_ROOT or /var/lib/mctrader/data)")
@click.option("--minio-endpoint", default=None, envvar="MINIO_ENDPOINT", help="MinIO endpoint URL")
@click.option("--minio-access-key", default=None, envvar="MINIO_ACCESS_KEY")
@click.option("--minio-secret-key", default=None, envvar="MINIO_SECRET_KEY")
def query_cmd(sql: str, data_root: str | None, minio_endpoint: str | None, minio_access_key: str | None, minio_secret_key: str | None) -> None:
    """Execute a DuckDB SQL query against local or MinIO Parquet files."""
    import os
    from pathlib import Path
    from mctrader_data.duckdb_reader import DuckDBReader, MinioConfig

    root = Path(data_root or os.environ.get("MCTRADER_DATA_ROOT", "/var/lib/mctrader/data"))
    minio = None
    if minio_endpoint:
        minio = MinioConfig(
            endpoint=minio_endpoint,
            access_key=minio_access_key or "",
            secret_key=minio_secret_key or "",
        )

    reader = DuckDBReader(root=root, minio=minio)
    with reader.open() as conn:
        result = conn.execute(sql)
        columns = [desc[0] for desc in result.description]
        rows = result.fetchall()
        col_widths = [max(len(col), max((len(str(row[i])) for row in rows), default=0)) for i, col in enumerate(columns)]
        header = "  ".join(col.ljust(col_widths[i]) for i, col in enumerate(columns))
        separator = "  ".join("-" * w for w in col_widths)
        print(header)
        print(separator)
        for row in rows:
            print("  ".join(str(row[i]).ljust(col_widths[i]) for i in range(len(columns))))


if __name__ == "__main__":  # pragma: no cover
    main()
