"""mctrader-data CLI — backfill orchestration (one-shot, MCT-15 first commit)."""

from __future__ import annotations

import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import click

from mctrader_market.types import Symbol, Timeframe

from mctrader_data.path import derive_partition_path, resolve_data_root
from mctrader_data.policy import PartialFailurePolicy


def _parse_iso_utc(value: str) -> datetime:
    if value.endswith("Z"):
        value = value[:-1] + "+00:00"
    dt = datetime.fromisoformat(value)
    if dt.tzinfo is None:
        raise click.BadParameter(f"naive datetime not allowed: {value!r}")
    if dt.utcoffset() != timedelta(0):
        raise click.BadParameter(f"non-UTC offset not allowed: {value!r}")
    return dt.replace(tzinfo=timezone.utc)


def _last_closed_boundary(now_utc: datetime, timeframe: Timeframe) -> datetime:
    """Return the most recent closed-bar boundary for the timeframe.

    1h: floor to UTC hour. 1d: KST midnight (UTC offset +9).
    """
    if timeframe is Timeframe.D1:
        kst = timezone(timedelta(hours=9))
        kst_now = now_utc.astimezone(kst)
        midnight_kst = kst_now.replace(hour=0, minute=0, second=0, microsecond=0)
        return midnight_kst.astimezone(timezone.utc)
    delta = timeframe.delta
    seconds = int(delta.total_seconds())
    epoch = int(now_utc.timestamp())
    floor_epoch = epoch - (epoch % seconds)
    return datetime.fromtimestamp(floor_epoch, tz=timezone.utc)


@click.group()
def main() -> None:
    """mctrader-data CLI."""


@main.command()
@click.option("--exchange", required=True, help='e.g. "bithumb"')
@click.option("--symbol", required=True, help='canonical "{quote}-{base}" e.g. "KRW-BTC"')
@click.option("--tf", "timeframe", required=True, type=click.Choice([t.value for t in Timeframe]))
@click.option("--days", type=int, default=None, help="N days back from --end (mutually exclusive with --start)")
@click.option("--start", "start_iso", type=str, default=None, help="ISO 8601 UTC inclusive")
@click.option("--end", "end_iso", type=str, default=None, help="ISO 8601 UTC exclusive (default = last closed bar)")
@click.option(
    "--policy",
    type=click.Choice([p.value for p in PartialFailurePolicy]),
    default=PartialFailurePolicy.HALT.value,
)
@click.option("--dry-run", is_flag=True, help="Print plan without fetching")
@click.option("--root", type=click.Path(path_type=Path), default=None)
@click.option("--snapshot-id", default=None, help="snapshot_id override (default = autogenerated)")
def backfill(
    exchange: str,
    symbol: str,
    timeframe: str,
    days: int | None,
    start_iso: str | None,
    end_iso: str | None,
    policy: str,
    dry_run: bool,
    root: Path | None,
    snapshot_id: str | None,
) -> None:
    """Backfill OHLCV candles for ``[start, end)`` half-open interval."""
    if days is not None and start_iso is not None:
        raise click.UsageError("--days and --start are mutually exclusive")

    sym = Symbol.from_string(symbol)
    tf = Timeframe(timeframe)

    end_utc = _parse_iso_utc(end_iso) if end_iso else _last_closed_boundary(datetime.now(timezone.utc), tf)
    if days is not None:
        if days <= 0:
            raise click.BadParameter("--days must be positive")
        start_utc = end_utc - timedelta(days=days)
    elif start_iso is not None:
        start_utc = _parse_iso_utc(start_iso)
    else:
        raise click.UsageError("must specify either --days or --start")

    if start_utc >= end_utc:
        raise click.BadParameter("start must be < end")

    root_resolved = resolve_data_root(root_override=root)
    partition_preview = derive_partition_path(
        root=root_resolved,
        exchange=exchange,
        symbol=sym,
        timeframe=tf,
        ts_utc=start_utc,
    )

    plan = {
        "exchange": exchange,
        "symbol": str(sym),
        "timeframe": tf.value,
        "start": start_utc.isoformat().replace("+00:00", "Z"),
        "end": end_utc.isoformat().replace("+00:00", "Z"),
        "policy": policy,
        "root": str(root_resolved),
        "snapshot_id": snapshot_id or "<auto>",
        "first_partition": str(partition_preview),
    }

    if dry_run:
        click.echo("[dry-run] Plan:")
        for key, value in plan.items():
            click.echo(f"  {key}: {value}")
        click.echo("[dry-run] No fetch performed.")
        return

    click.echo("[backfill] adapter implementation arrives via mctrader-market-bithumb (MCT-14).")
    click.echo("[backfill] First-commit storage scaffold only.")
    for key, value in plan.items():
        click.echo(f"  {key}: {value}")
    sys.exit(0)


if __name__ == "__main__":  # pragma: no cover
    main()
